E2E Tests Workflows and Tests
inworld-ai/inworld-nodejs-sdk pull request #150
Opened 2024-05-30 18:16 UTC by russinworld

## Description

- [NOT DONE] Updated workflows to have Allure test reporting integration
- Updated `TESTME.md`
- Added test scripts for `connection`, `goals`, and `knowledge `suites

## Related Issue (for external contributions)

## Related Ticket (for Inworld.ai developers)

## Screenshots (if appropriate)

## Checklist before requesting a review

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation

2024-05-30 19:02 UTC, RobHCo commented on TESTME.md
> +> To run a single test, write the exact test file name ex. `e2e/text/text.spec.ts`.
You'll want to update these examples since that file/directory is being removed

2024-05-30 19:10 UTC, RobHCo commented on e2e/goals/trigger.spec.ts
> +test('Should tell player to visit castle and retrieve jewel', async () => {
I might be mistaken, but this seems like it's using a goal intent instead of a trigger, similar to the verbatim test.  Would likely be redundant in this form.

2024-05-30 19:28 UTC, russinworld commented on e2e/goals/trigger.spec.ts
> +test('Should tell player to visit castle and retrieve jewel', async () => {
In this test I am just checking that the NPC can reply with auto generated text that contains the word jewel, as that is the main task of the quest. As long as the NPC provides text with that key phrase, it will pass. Versus, in verbatim, I am ensuring its always saying a specific piece of text.

2024-05-30 20:37 UTC, tshashkova requested changes
I have additional suggestion. Let's try to run this test on different platforms
For example, on Windows

2024-05-30 20:37 UTC, tshashkova commented on .github/workflows/demand.yml
> +name: On Demand Test Run - PROD
What it the difference between on demand and daily workflow?
I see that you upload test results to Allure only for On Demand case
But I suppose it should be done for both scenarios
And in this case It seems that we can reuse almost all source code for both actions
The only one difference is how we run the workflow. And the list of file that should be tested

2024-05-30 20:37 UTC, tshashkova commented on .github/workflows/demand.yml
> +            ALLURE_TOKEN:inworld-ai-prod/allure-token
It doesn't look like a secret, it's not encoded string
But if it's a secret it should be kept here in open form

2024-05-30 20:37 UTC, tshashkova commented on .github/workflows/demand.yml
> +          npm install jest-html-reporter
I don't like that we install these packages and @inworld/nodejs-sdk manually
Isn't is possible to use separate package.json to keep all test dependencies?

And another point that I'm interesting in is how to test not published nodejs-sdk. I suppose it would be nice to test PR that we want to merge

2024-05-30 20:37 UTC, tshashkova commented on .github/workflows/demand.yml
>          run: npm install @inworld/nodejs-sdk
Let's use yarn everywhere. All prev workflow use yarn and below in the this file you also use yarn (yarn test)
So let's keep one style

2024-05-30 20:37 UTC, tshashkova commented on TESTME.md
> +> To run all tests use only an asterisk ex. `*`, `__tests__/*`, `e2e/*`
From my point of view it should be easy to run all test. I.e. running all test should be default behaviour, where I just need to press run without any typing

2024-05-30 20:37 UTC, tshashkova commented on .github/workflows/daily.yml
> +      INWORLD_E2E_SCENE_AUDIO: ${{ vars.INWORLD_E2E_SCENE_AUDIO }}
INWORLD_E2E_SCENE_SCENE looks weird and not clear
And as I see it's used for audio test case too
INWORLD_E2E_SCENE_TEXT looks like it's a text itself that is used for for test, rather than scene name
Need to find better names

2024-05-30 20:37 UTC, tshashkova commented on TESTME.md
> +Execute the following command to run E2E tests:
Locally we mostly need to test not published version
So it should explained how to do it
I.e. that we need to link this package version like it's done below. Maybe we need move and reuse information about linking for this section and the Manual tests one

2024-05-30 20:37 UTC, tshashkova commented on TESTME.md
> +INWORLD_E2E_SCENE_SCENE=
It would be easier if you create env.sample file that will contain these variables

2024-05-30 20:37 UTC, tshashkova commented on e2e/connection/audio.spec.ts
> +}, 10000);
I think we need to test it more deeper
I.e. not just the fact that we received response, but the structure of packets that we sent and received

2024-05-30 20:37 UTC, tshashkova commented on e2e/e2e_helpers.ts
> +            reject(err);
It's not an error
It's a technical error code (https://docs.inworld.ai/docs/tutorial-integrations/node/api/#error-handling)
For example, we close connection we get CANCELLED code

FYI: connection is closed automatically. You don't need to do it manually

2024-05-30 20:37 UTC, tshashkova commented on e2e/connection/text.spec.ts
> +// import 'dotenv/config';
Why it's commented?

2024-05-31 16:06 UTC, russinworld commented on TESTME.md
> +INWORLD_E2E_SCENE_SCENE=
Should this file be stored in the e2e folder?

2024-05-31 16:09 UTC, russinworld commented on TESTME.md
> +> To run all tests use only an asterisk ex. `*`, `__tests__/*`, `e2e/*`
I can change the GitHub workflow to run all tests by default however that is just the syntax I believe required to run the tests since that field can not be blank in the GitHub input

2024-05-31 16:11 UTC, russinworld commented on .github/workflows/demand.yml
> +name: On Demand Test Run - PROD
Yes, I plan on integrating Allure results to both workflows, I just had only gained access to the Google Secret yesterday late and did not have enough time to add it to both workflows as I am still currently working on fixing some issues.

2024-05-31 16:12 UTC, russinworld commented on .github/workflows/demand.yml
> +            ALLURE_TOKEN:inworld-ai-prod/allure-token
I just kept this syntax the same as the workflow in the other inworld-fe repo. As they also pull a google secret the same way

2024-06-03 17:11 UTC, russinworld commented on e2e/connection/audio.spec.ts
> +}, 10000);
Good point, I think we can test this in the next PR for improvements

2024-06-03 17:13 UTC, russinworld commented on TESTME.md
> +Execute the following command to run E2E tests:
I think this would be good to add for the next PR where I will add the option to test on PROD, STAGING, DEV envs

2024-06-03 17:48 UTC, tshashkova reviewed
Could you please setup your IDE to keep only one empty line at the end of file on save?
It will prevent warning that GitHub displays
In fact for Web SDK I added review check for this case (https://github.com/inworld-ai/inworld-web-sdk/blob/main/.github/workflows/reviewdog.yml#L48) and I'm going to add it for Node.js one too. It would be easier to detect this warning automatically

2024-06-03 17:48 UTC, tshashkova commented on TESTME.md
> +> To run all tests use only an asterisk ex. `*`, `__tests__/*`, `e2e/*`
Maybe * should be used as default value, it also works

2024-06-03 20:49 UTC, tshashkova approved these changes

2024-06-03 20:49 UTC, merged