Test 75 add test to cover voice interaction
inworld-ai/inworld-nodejs-sdk pull request #220
Opened 2024-07-04 18:31 UTC by russinworld

## Description
- Added new test to assert packets for sending audio
- Added new wrapper `sendAudio`

## Related Issue (for external contributions)

## Related Ticket (for Inworld.ai developers)

## Screenshots (if appropriate)

## Checklist before requesting a review

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation

2024-07-06 06:52 UTC, tshashkova requested changes

2024-07-06 06:52 UTC, tshashkova commented on e2e/e2e_helpers.ts
> +        sendAudio: async (audio: string) => {
Let's move `sendAudio` and `sendText` from here
I mean inline usage is too large and it's complicated to read the code
While we had sendText only it was more or less ok, but now it's obviously that need to rewrite it better
So it should look like:
```

resolve({
  close: connection.close.bind(connection),
  sendText: sendText(...),
  sendAudio: sendAudio(...),
});
```

2024-07-06 06:52 UTC, tshashkova commented on e2e/e2e_helpers.ts
> +              connection.sendAudioSessionEnd();
You don't need to do it here
Just send session end after the silence inside `sendAudio` method

2024-07-08 13:32 UTC, russinworld commented on e2e/e2e_helpers.ts
> +        sendAudio: async (audio: string) => {
Don't these functions have to be defined inline since a lot of the code is only available within the scope of the openConnectionManually method? If it were to be a function defined outside, you would need to pass in the connection object, config, byPacketId, etc. Since this is a wrapper, wouldn't that also mean you need to pass in those parameters from the actual test spec then as well?

2024-07-10 19:57 UTC, tshashkova approved these changes

2024-07-10 19:57 UTC, merged