feat: init latency added
inworld-ai/inworld-nodejs-sdk pull request #281
Opened 2024-09-18 13:52 UTC by Disfractal

## Description

## Related Issue (for external contributions)

## Related Ticket (for Inworld.ai developers)

## Screenshots (if appropriate)

## Checklist before requesting a review

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation

2024-09-18 18:21 UTC, tshashkova requested changes
@Disfractal Don't forget to add record to CHANGELOG.md

2024-09-18 18:21 UTC, tshashkova commented on src/services/connection.service.ts
> +        this.sendPingPongResponse(inworldPacket);
Build packet inside pong method
I.e. here it's enough to do:
`this.send(() => this.getEventFactory().pong(packet));`

And in event.ts pong method will look like:

```
   pong(initialPacket: ProtoPacket): ProtoPacket {
    const packetId = initialPacket.getPacketId();

    const event = new LatencyReportEvent().setPingPong(
      new PingPongReport()
        .setPingPacketId(
          new PacketId()
            .setPacketId(packetId.getPacketId())
            .setConversationId(packetId.getConversationId())
            .setInteractionId(packetId.getInteractionId())
            .setCorrelationId(packetId.getCorrelationId()),
        )
        .setPingTimestamp(
          initialPacket.getLatencyReport().getPingPong().getPingTimestamp(),
        )
        .setType(PingPongReport.Type.PONG),
    );

    return this.baseProtoPacket({
      utteranceId: false,
      interactionId: false,
    }).setLatencyReport(event);
  }
```

I.e. we keep all implementation details of packets that we send inside event.ts

2024-09-18 18:21 UTC, tshashkova commented on src/entities/packets/inworld_packet.entity.ts
> +    return this.isLatencyReport() && this.latencyReport.pingPong;
It looks like boolean response is expected
So need to write it in the slightly different way

`return this.isLatencyReport() && !!this.latencyReport.pingPong;`

The same for `isPerceivedLatencyReport` method

2024-09-18 18:21 UTC, tshashkova commented on src/entities/packets/latency/latency_report.entity.ts
> +      ...(proto.getPingPong() && {
`proto.hasPingPong()`

2024-09-18 18:21 UTC, tshashkova commented on src/entities/packets/latency/latency_report.entity.ts
> +      ...(proto.getPerceivedLatency() && {
`proto.hasPerceivedLatency()`

2024-09-18 18:21 UTC, tshashkova commented on src/entities/packets/latency/ping_pong_report.entity.ts
> +        PingPongReportType.fromProto(proto.getType()),
It's just an enum and it's ok to convert types here without additional class
It will reduce complexity of data structure keeping it here

2024-09-18 18:21 UTC, tshashkova commented on src/entities/packets/latency/perceived_latency_report.ts
> +      ),
Again, let's convert types here without placing it in the separate file

2024-09-18 18:21 UTC, tshashkova commented on src/entities/packets/latency/perceived_latency_report.ts
> +      latency: Number(proto.getLatency()),
I have a doubt that we can convert it to number, because original Google duration is a object of 2 numbers
```
export namespace Duration {
    export type AsObject = {
        seconds: number;
        nanos: number;
    };
}
```
So, I suppose we need to keep this structure for our internal representation as well

2024-09-18 18:21 UTC, tshashkova commented on src/services/connection.service.ts
> +        this.sendPingPongResponse(inworldPacket);
And will allow you to test easily pong packet independently of conversation service

2024-10-29 02:27 UTC, Disfractal reviewed
Added the record to CHANGELOG

2024-10-29 17:51 UTC, tshashkova approved these changes

2024-10-29 18:14 UTC, merged