feat: start of adding pingpong test
inworld-ai/inworld-nodejs-sdk pull request #321
Opened 2024-11-26 19:52 UTC by Disfractal

This PR adds the tests for PingPong and PercievedLatency

2024-11-26 21:11 UTC, tshashkova commented on __tests__/services/connection.service.spec.ts
> +    const sendPingPongResponse = jest.spyOn(connection, 'sendPingPongResponse');
It's a private method, you can't spy on it
And it's just a some kind of proxy
Let's spy on `write` instead
```
    const write = jest
      .spyOn(ClientDuplexStreamImpl.prototype, 'write')
      .mockImplementation(jest.fn());
```

2024-11-26 21:11 UTC, tshashkova commented on __tests__/services/connection.service.spec.ts
> +    const sendPingPongResponse = jest.spyOn(connection, 'sendPingPongResponse');
In this case you need to check that `write` was called with proto representation of pong

2024-11-26 21:11 UTC, tshashkova commented on __tests__/services/connection.service.spec.ts
> +    const sendPingPongResponse = jest.spyOn(connection, 'sendPingPongResponse');
And `sendPong` spyOn looks excessive
It's enough to check that we sent correct proto packet

2024-11-26 21:11 UTC, tshashkova commented on __tests__/services/connection.service.spec.ts
> +    const sendPingPongResponse = jest.spyOn(connection, 'sendPingPongResponse');
Of course it would be better just to spy on `connection.send`, but it takes the getPacket fn, that generates the proto packet. Not the packet itself. It was implemented in this way for some reasons.
So because we can't spy on `connection.send` and check packet structure, we have to spy on `stream.write` (ClientDuplexStreamImpl) instead

2024-12-02 16:38 UTC, Disfractal commented on __tests__/services/connection.service.spec.ts
> +    const sendPingPongResponse = jest.spyOn(connection, 'sendPingPongResponse');
I made the change but write is returning a packet that looks like it's from another test.

2024-12-10 18:26 UTC, tshashkova requested changes

2024-12-10 18:26 UTC, tshashkova commented on __tests__/services/connection.service.spec.ts
> +    await connection.send(() => {
await connection.send(() => packetRequest);

2024-12-10 18:26 UTC, tshashkova commented on __tests__/services/connection.service.spec.ts
> +    await connection.send(() => {
Latency report is sent by SDK, you don't to send it from test, you need to check that it's sent somehow

- Client sends text event
- Server returns response (you call emit to simulate it)
- SDK calculate time difference and send latency report to the the server

2024-12-11 21:40 UTC, Disfractal reviewed
Please review

2024-12-16 16:40 UTC, tshashkova approved these changes

2024-12-16 16:40 UTC, merged